FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY *.conf /etc/nginx/conf.d/
#COPY portfolio.conf /etc/nginx/conf.d
#COPY wordcounter.conf /etc/nginx/conf.d/
#COPY addressbook.conf /etc/nginx/conf.d/
#COPY learninglog.conf /etc/nginx/conf.d/
#COPY helloworld.conf /etc/nginx/conf.d/
#COPY flaskblog.conf /etc/nginx/conf.d/
#COPY flasktaskr.conf /etc/nginx/conf.d/
#COPY producthunt.conf /etc/nginx/conf.d/
